export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
] as const;

export const REQUEST_STATUSES = {
  PENDING: { label: "Pending Review", color: "bg-amber-100 text-amber-800 dark:bg-amber-950/60 dark:text-amber-300" },
  ACCEPTED: { label: "Accepted", color: "bg-blue-100 text-blue-800 dark:bg-blue-950/60 dark:text-blue-300" },
  IN_PROGRESS: { label: "In Progress", color: "bg-indigo-100 text-indigo-800 dark:bg-indigo-950/60 dark:text-indigo-300" },
  WAITING_FOR_USER: { label: "Action Needed from Citizen", color: "bg-orange-100 text-orange-800 dark:bg-orange-950/60 dark:text-orange-300" },
  COMPLETED: { label: "Completed", color: "bg-emerald-100 text-emerald-800 dark:bg-emerald-950/60 dark:text-emerald-300" },
  CANCELLED: { label: "Cancelled", color: "bg-zinc-100 text-zinc-800 dark:bg-zinc-800 dark:text-zinc-300" },
  REJECTED: { label: "Rejected", color: "bg-red-100 text-red-800 dark:bg-red-950/60 dark:text-red-300" },
} as const;

export const OFFICIAL_DISCLAIMER =
  "SevaDesk is an independent digital information and assistance facilitation platform. It is not affiliated with, endorsed by, or representing the Government of India or any State Government department. All applications typed on this platform are citizen-prepared draft formats. Statutory official fees and timelines are subject to state revenue rules.";
